### ISSUE TITLE
broken website

### ISSUE THREAD

**Issue by samcrudge** [codesupport/old-website-frontend#48]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected Behaviour**
actually show the sub headings.

**Screenshots**
![Screenshot 2020-03-30 at 11 58 37 (2)](https://user-images.githubusercontent.com/37799019/77927414-1c657880-729f-11ea-81f4-28acd07de36a.png)
![Screenshot 2020-03-30 at 11 57 23 (2)](https://user-images.githubusercontent.com/37799019/77927423-1ec7d280-729f-11ea-97cd-2cae9b330f79.png)

**Tech Specs**
 - OS: [e.g. macOS]
 - Browser google chrome
 - Version current

**Additional Info**
Any other information that you believe might be helpful.

**Comment by AtrumAmantus** [comment]
Horizontal scroll appears apparently due to 100vw setting on `.modal-container, nav` and `.container`
Additional reactive design defects appear to occur from use of static width definitions
Not sure what causes the horizontal bar to 'stick', but can confirm it does so on chrome in ubuntu as well. 
Ubuntu 18.04.4 LTS
Chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by LamboCreeper** [comment]
I have some ideas on what may be causing this. Will take a look at the weekend. Thanks for bringing it to our attention.
